/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/


// ---------- HardwareConfig ----------

// EnumValue DeviceType

typedef enum {
  DEVICETYPE_BASE_STATION = 0,
  DEVICETYPE_TEMPERATURE_SENSOR = 20,
  DEVICETYPE_POWER_SWITCH = 40,
  DEVICETYPE_DIMMER = 60
} DeviceTypeEnum;

#define EEPROM_DEVICETYPE_BYTE 0
#define EEPROM_DEVICETYPE_BIT 0
#define EEPROM_DEVICETYPE_LENGTH_BITS 8

// UIntValue OsccalMode

#define EEPROM_OSCCALMODE_BYTE 1
#define EEPROM_OSCCALMODE_BIT 0
#define EEPROM_OSCCALMODE_LENGTH_BITS 8
#define EEPROM_OSCCALMODE_MINVAL 0
#define EEPROM_OSCCALMODE_MAXVAL 255

// Reserved area with 48 bits


// ---------- GenericConfig ----------

// UIntValue DeviceID

#define EEPROM_DEVICEID_BYTE 8
#define EEPROM_DEVICEID_BIT 0
#define EEPROM_DEVICEID_LENGTH_BITS 12
#define EEPROM_DEVICEID_MINVAL 0
#define EEPROM_DEVICEID_MAXVAL 4095

// Reserved area with 4 bits

// UIntValue PacketCounter

#define EEPROM_PACKETCOUNTER_BYTE 10
#define EEPROM_PACKETCOUNTER_BIT 0
#define EEPROM_PACKETCOUNTER_LENGTH_BITS 24
#define EEPROM_PACKETCOUNTER_MINVAL 0
#define EEPROM_PACKETCOUNTER_MAXVAL 16777215

// Reserved area with 152 bits

// ByteArray AesKey

#define EEPROM_AESKEY_BYTE 32
#define EEPROM_AESKEY_BIT 0
#define EEPROM_AESKEY_LENGTH_BYTES 32


// ---------- TemperatureSensorConfig ----------

// EnumValue TemperatureSensorType

typedef enum {
  TEMPERATURESENSORTYPE_NOSENSOR = 0,
  TEMPERATURESENSORTYPE_SHT15 = 1
} TemperatureSensorTypeEnum;

#define EEPROM_TEMPERATURESENSORTYPE_BYTE 64
#define EEPROM_TEMPERATURESENSORTYPE_BIT 0
#define EEPROM_TEMPERATURESENSORTYPE_LENGTH_BITS 8

// EnumValue BrightnessSensorType

typedef enum {
  BRIGHTNESSSENSORTYPE_NOSENSOR = 0,
  BRIGHTNESSSENSORTYPE_PHOTOCELL = 1
} BrightnessSensorTypeEnum;

#define EEPROM_BRIGHTNESSSENSORTYPE_BYTE 65
#define EEPROM_BRIGHTNESSSENSORTYPE_BIT 0
#define EEPROM_BRIGHTNESSSENSORTYPE_LENGTH_BITS 8

// Reserved area with 3568 bits

// overall length: 4096 bits

