/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#ifndef _E2P_TEMPSENSOR_H
#define _E2P_TEMPSENSOR_H

// E2P Block "TempSensor"
// ======================
// Start offset (bit): 512
// Overall block length: 3584 bits

// EnumValue TemperatureSensorType

typedef enum {
  TEMPERATURESENSORTYPE_NOSENSOR = 0,
  TEMPERATURESENSORTYPE_SHT15 = 1
} TemperatureSensorTypeEnum;

// Set TemperatureSensorType (EnumValue)
// Byte offset: 64, bit offset: 0, length bits 8
static inline void e2p_tempsensor_set_temperaturesensortype(TemperatureSensorTypeEnum val)
{
  eeprom_write_UIntValue(64, 0, 8, val);
}

// Get TemperatureSensorType (EnumValue)
// Byte offset: 64, bit offset: 0, length bits 8
static inline TemperatureSensorTypeEnum e2p_tempsensor_get_temperaturesensortype(void)
{
  return eeprom_read_UIntValue8(64, 0, 8, 0, 255);
}

// EnumValue BrightnessSensorType

typedef enum {
  BRIGHTNESSSENSORTYPE_NOSENSOR = 0,
  BRIGHTNESSSENSORTYPE_PHOTOCELL = 1
} BrightnessSensorTypeEnum;

// Set BrightnessSensorType (EnumValue)
// Byte offset: 65, bit offset: 0, length bits 8
static inline void e2p_tempsensor_set_brightnesssensortype(BrightnessSensorTypeEnum val)
{
  eeprom_write_UIntValue(65, 0, 8, val);
}

// Get BrightnessSensorType (EnumValue)
// Byte offset: 65, bit offset: 0, length bits 8
static inline BrightnessSensorTypeEnum e2p_tempsensor_get_brightnesssensortype(void)
{
  return eeprom_read_UIntValue8(65, 0, 8, 0, 255);
}

// Reserved area with 3568 bits


#endif /* _E2P_TEMPSENSOR_H */
