/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#ifndef _E2P_TEMPSENSOR_H
#define _E2P_TEMPSENSOR_H


// ---------- TempSensor ----------
// Start offset (bit): 512
// Overall block length: 3584 bits

// EnumValue TemperatureSensorType

typedef enum {
  TEMPERATURESENSORTYPE_NOSENSOR = 0,
  TEMPERATURESENSORTYPE_SHT15 = 1
} TemperatureSensorTypeEnum;

#define EEPROM_TEMPERATURESENSORTYPE_BYTE 64
#define EEPROM_TEMPERATURESENSORTYPE_BIT 0
#define EEPROM_TEMPERATURESENSORTYPE_LENGTH_BITS 8

// EnumValue BrightnessSensorType

typedef enum {
  BRIGHTNESSSENSORTYPE_NOSENSOR = 0,
  BRIGHTNESSSENSORTYPE_PHOTOCELL = 1
} BrightnessSensorTypeEnum;

#define EEPROM_BRIGHTNESSSENSORTYPE_BYTE 65
#define EEPROM_BRIGHTNESSSENSORTYPE_BIT 0
#define EEPROM_BRIGHTNESSSENSORTYPE_LENGTH_BITS 8

// Reserved area with 3568 bits


#endif /* _E2P_TEMPSENSOR_H */
