/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#ifndef _E2P_HARDWARE_H
#define _E2P_HARDWARE_H


// ---------- Hardware ----------
// Start offset (bit): 0
// Overall block length: 64 bits

// EnumValue DeviceType

typedef enum {
  DEVICETYPE_BASESTATION = 0,
  DEVICETYPE_TEMPSENSOR = 20,
  DEVICETYPE_POWERSWITCH = 40,
  DEVICETYPE_DIMMER = 60,
  DEVICETYPE_THERMOSTAT = 80
} DeviceTypeEnum;

#define EEPROM_DEVICETYPE_BYTE 0
#define EEPROM_DEVICETYPE_BIT 0
#define EEPROM_DEVICETYPE_LENGTH_BITS 8

// UIntValue OsccalMode

#define EEPROM_OSCCALMODE_BYTE 1
#define EEPROM_OSCCALMODE_BIT 0
#define EEPROM_OSCCALMODE_LENGTH_BITS 8
#define EEPROM_OSCCALMODE_MINVAL 0
#define EEPROM_OSCCALMODE_MAXVAL 255

// Reserved area with 48 bits


#endif /* _E2P_HARDWARE_H */
