/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#ifndef _E2P_THERMOSTAT_H
#define _E2P_THERMOSTAT_H


// ---------- Thermostat ----------
// Start offset (bit): 512
// Overall block length: 7680 bits

// UIntValue BaseStationPacketCounter

#define EEPROM_BASESTATIONPACKETCOUNTER_BYTE 64
#define EEPROM_BASESTATIONPACKETCOUNTER_BIT 0
#define EEPROM_BASESTATIONPACKETCOUNTER_LENGTH_BITS 24
#define EEPROM_BASESTATIONPACKETCOUNTER_MINVAL 0
#define EEPROM_BASESTATIONPACKETCOUNTER_MAXVAL 16777215

// Reserved area with 7656 bits


#endif /* _E2P_THERMOSTAT_H */
