/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#ifndef _E2P_BASESTATION_H
#define _E2P_BASESTATION_H


// ---------- BaseStation ----------
// Start offset (bit): 512
// Overall block length: 7680 bits

// UIntValue AesKeyCount

#define EEPROM_AESKEYCOUNT_BYTE 64
#define EEPROM_AESKEYCOUNT_BIT 0
#define EEPROM_AESKEYCOUNT_LENGTH_BITS 8
#define EEPROM_AESKEYCOUNT_MINVAL 1
#define EEPROM_AESKEYCOUNT_MAXVAL 16

// ByteArray AesKeys

#define EEPROM_AESKEYS_BYTE 65
#define EEPROM_AESKEYS_BIT 0
#define EEPROM_AESKEYS_LENGTH_BYTES 512

// Reserved area with 3576 bits


#endif /* _E2P_BASESTATION_H */
