/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#include "packet_header.h"
#include "e2p_access.h"

// Message Group "tempsensor"
// ==========================
// MessageGroupID: 10


// Message "tempsensor_tempstatus"
// -------------------------------
// MessageGroupID: 10
// MessageID: 1
// MessageType: 0
// Data fields: Temperature, Humidity, Brightness
// length: 113 bits (needs 15 bytes)

// Function to initialize header for the message.
static inline void pkg_header_init_tempsensor_tempstatus(void)
{
  memset(&bufx[0], 0, sizeof(bufx));
  pkg_header_set_messagegroupid(10);
  pkg_header_set_messageid(1);
  pkg_header_set_messagetype(0);
}

// Function to set CRC value after all data fields are set.
static inline void pkg_header_crc32_tempsensor_tempstatus(void)
{
  pkg_header_set_crc32(crc32(bufx + 4, 12));
}

// Set Temperature (IntValue)
// byte 10, bit 0, length bits 16, min val -32768, max val 32767
static inline void msg_tempsensor_tempstatus_set_temperature(int32_t val)
{
  array_write_IntValue(10, 0, 16, val, bufx);
}

// Set Humidity (UIntValue)
// byte 12, bit 0, length bits 10, min val 0, max val 1000
static inline void msg_tempsensor_tempstatus_set_humidity(uint32_t val)
{
  array_write_UIntValue(12, 0, 10, val, bufx);
}

// Set Brightness (UIntValue)
// byte 13, bit 2, length bits 7, min val 0, max val 100
static inline void msg_tempsensor_tempstatus_set_brightness(uint32_t val)
{
  array_write_UIntValue(13, 2, 7, val, bufx);
}

