/*
* This file is part of smarthomatic, http://www.smarthomatic.org.
* Copyright (c) 2013 Uwe Freese
*
* smarthomatic is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
*
* smarthomatic is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
* Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
*
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* ! WARNING: This file is generated by the SHC EEPROM editor and should !
* ! never be modified manually.                                         !
* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#ifndef _PACKET_HEADEREXT_SET_H
#define _PACKET_HEADEREXT_SET_H

#include "packet_header.h"

// Set ReceiverID (UIntValue)
// Offset: 9, 0, length bits 12, min val 0, max val 4095
static inline void pkg_headerext_set_set_receiverid(uint32_t val)
{
  array_write_UIntValue(9, 0, 12, val, bufx);
}

// Set MessageGroupID (UIntValue)
// Offset: 10, 4, length bits 7, min val 0, max val 127
static inline void pkg_headerext_set_set_messagegroupid(uint32_t val)
{
  array_write_UIntValue(10, 4, 7, val, bufx);
}

// Set MessageID (UIntValue)
// Offset: 11, 3, length bits 4, min val 0, max val 15
static inline void pkg_headerext_set_set_messageid(uint32_t val)
{
  array_write_UIntValue(11, 3, 4, val, bufx);
}


// overall length: 95 bits
// message data follows: yes

#endif /* _PACKET_HEADEREXT_SET_H */
