#
# This file is part of smarthomatic, http://www.smarthomatic.com.
# Copyright (c) 2013 Uwe Freese
#
# smarthomatic is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# smarthomatic is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
#

# Default target
all: elf hex eep lss sym fuse size

# Target files
elf: $(OBJDIR)/$(TARGET).elf
hex: $(BINDIR)/$(TARGET).hex
eep: $(BINDIR)/$(TARGET).eep
lss: $(OBJDIR)/$(TARGET).lss
sym: $(OBJDIR)/$(TARGET).sym


# Size of build
size: $(OBJDIR)/$(TARGET).elf
	@echo
	@echo "Image size:"
	@$(SIZE) -d -B $(OBJDIR)/$(TARGET).elf

# Clean project.
clean:
	$(REMOVEDIR) $(OBJDIR)
distclean: clean
	$(REMOVEDIR) $(BINDIR)

# create fuse hex files by dumping the relevant section	from fuses.hex
fuse: $(OBJDIR)/$(TARGET).elf
	$(eval LFUSE = $(shell $(OBJDUMP) -s -j .fuse $(OBJDIR)/$(TARGET).elf | $(TAIL) -n1 | $(AWK) '{print(toupper(substr($$2,1,2)))}'))
	$(eval HFUSE = $(shell $(OBJDUMP) -s -j .fuse $(OBJDIR)/$(TARGET).elf | $(TAIL) -n1 | $(AWK) '{print(toupper(substr($$2,3,2)))}'))
	$(eval EFUSE = $(shell $(OBJDUMP) -s -j .fuse $(OBJDIR)/$(TARGET).elf | $(TAIL) -n1 | $(AWK) '{print(toupper(substr($$2,5,2)))}'))
	@echo
	@echo "Fuses:"
	@echo "  LFUSE = 0x$(LFUSE)"
	@echo "  HFUSE = 0x$(HFUSE)"
	@echo "  EFUSE = 0x$(EFUSE)"
	@echo -n "0x$(LFUSE)">$(BINDIR)/lfuse.txt
	@echo -n "0x$(HFUSE)">$(BINDIR)/hfuse.txt
	@echo -n "0x$(EFUSE)">$(BINDIR)/efuse.txt

# create fuses, possibility 2
#fuse: $(OBJDIR)/$(TARGET).elf
#	$(OBJCOPY) -j .fuse -O ihex $(OBJDIR)/$(TARGET).elf $(OBJDIR)/fuses.hex --change-section-lma .fuse=0
#	srec_cat $(OBJDIR)/fuses.hex -Intel -crop 0x00 0x01 -offset  0x00 -O $(BINDIR)/lfuse.hex -Intel
#	srec_cat $(OBJDIR)/fuses.hex -Intel -crop 0x01 0x02 -offset -0x01 -O $(BINDIR)/hfuse.hex -Intel
#	srec_cat $(OBJDIR)/fuses.hex -Intel -crop 0x02 0x03 -offset -0x02 -O $(BINDIR)/efuse.hex -Intel

# Program (avrdude)
program:
	$(AVRDUDE) -p $(AVRDUDEMCU) -U flash:w:$(BINDIR)/$(TARGET).hex
	
program_fuses: fuse
	$(AVRDUDE) -p m328p -U lfuse:w:0x$(LFUSE):m -U hfuse:w:0x$(HFUSE):m -U efuse:w:0x$(EFUSE):m

read_fuses:
	$(AVRDUDE) -p m328p -U lfuse:r:-:b -U hfuse:r:-:b -U efuse:r:-:b

# Listing of phony targets.
.PHONY : all elf hex eep lss sym clean distclean
