#
# This file is part of smarthomatic, http://www.smarthomatic.org.
# Copyright (c) 2013 Uwe Freese
#
# smarthomatic is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# smarthomatic is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
#

# Default target
all: elf hex lss sym fuse size

# Target files
elf: $(OBJDIR)/$(TARGET).elf
hex: $(BINDIR)/$(TARGET).hex
eep: $(BINDIR)/$(TARGET).eep
lss: $(OBJDIR)/$(TARGET).lss
sym: $(OBJDIR)/$(TARGET).sym

# Size of build
size: $(OBJDIR)/$(TARGET).elf
	@echo
	@$(SIZE) -d -C --mcu=$(MCU) $(OBJDIR)/$(TARGET).elf

# Clean project
clean:
	$(REMOVEDIR) $(OBJDIR)

# Clean + build project
cleanbuild: clean all

# create fuse hex files by dumping the relevant section	from fuses.hex
fuse: $(OBJDIR)/$(TARGET).elf
	$(eval LFUSE = $(shell $(OBJDUMP) -s -j .fuse $(OBJDIR)/$(TARGET).elf | $(TAIL) -n1 | $(AWK) '{print(toupper(substr($$2,1,2)))}'))
	$(eval HFUSE = $(shell $(OBJDUMP) -s -j .fuse $(OBJDIR)/$(TARGET).elf | $(TAIL) -n1 | $(AWK) '{print(toupper(substr($$2,3,2)))}'))
	$(eval EFUSE = $(shell $(OBJDUMP) -s -j .fuse $(OBJDIR)/$(TARGET).elf | $(TAIL) -n1 | $(AWK) '{print(toupper(substr($$2,5,2)))}'))
	@echo
	@echo "Fuses:"
	@echo "  LFUSE = 0x$(LFUSE)"
	@echo "  HFUSE = 0x$(HFUSE)"
	@echo "  EFUSE = 0x$(EFUSE)"
	
	@echo x | $(AWK) '{printf "\x$(LFUSE)"}' > $(BINDIR)/lfuse.bin
	@echo x | $(AWK) '{printf "\x$(HFUSE)"}' > $(BINDIR)/hfuse.bin
	@echo x | $(AWK) '{printf "\x$(EFUSE)"}' > $(BINDIR)/efuse.bin
	
# create fuses, possibility 2
#fuse2: $(OBJDIR)/$(TARGET).elf
#	$(OBJCOPY) -j .fuse -O ihex $(OBJDIR)/$(TARGET).elf $(OBJDIR)/fuses.hex --change-section-lma .fuse=0
#	srec_cat $(OBJDIR)/fuses.hex -Intel -crop 0x00 0x01 -offset  0x00 -O $(BINDIR)/lfuse.hex -Intel
#	srec_cat $(OBJDIR)/fuses.hex -Intel -crop 0x01 0x02 -offset -0x01 -O $(BINDIR)/hfuse.hex -Intel
#	srec_cat $(OBJDIR)/fuses.hex -Intel -crop 0x02 0x03 -offset -0x02 -O $(BINDIR)/efuse.hex -Intel

# Program (avrdude)
program:
	$(AVRDUDE) -p $(AVRDUDEMCU) -U flash:w:$(BINDIR)/$(TARGET).hex
	
program_fuses: fuse
	$(AVRDUDE) -p $(AVRDUDEMCU) -U lfuse:w:$(BINDIR)/lfuse.bin:r -U hfuse:w:$(BINDIR)/hfuse.bin:r -U efuse:w:$(BINDIR)/efuse.bin:r

read_fuses:
	$(AVRDUDE) -p $(AVRDUDEMCU) -U lfuse:r:-:b -U hfuse:r:-:b -U efuse:r:-:b

# Listing of phony targets.
.PHONY : all elf hex eep lss sym clean distclean
