#
# This file is part of smarthomatic, http://www.smarthomatic.org.
# Copyright (c) 2013 Uwe Freese
#
# smarthomatic is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# smarthomatic is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with smarthomatic. If not, see <http://www.gnu.org/licenses/>.
#

# Object files directory
OBJDIR = build
BINDIR = bin
#CCDIR = /usr/local/CrossPack-AVR/bin/

# Define programs and commands.
SHELL = sh
CC = $(CCDIR)avr-gcc
OBJCOPY = $(CCDIR)avr-objcopy
OBJDUMP = $(CCDIR)avr-objdump
SIZE = $(CCDIR)avr-size
NM = $(CCDIR)avr-nm
REMOVE = rm -f
REMOVEDIR = rm -rf
COPY = cp
TAIL = tail
AWK = awk

# Define your avrdude path, programmer settings and COM port for avrdude
# here, or set up your avrdude.rc (Windows) or ~/.avrduderc (Linux).
AVRDUDE = avrdude
